name: Secrets workflow
env:
  API_CSPROJ_PATH: src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj

on:
  pull_request:
    branches: [ "main" ]

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo ${{ secrets.API_CSPROJ_PATH }}
